# Generated by Django 5.0.3 on 2024-04-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-Name'], 'verbose_name_plural': 'Student'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='stud',
        ),
    ]
